#!/bin/bash
#-----------------------
# Testing quantum-daemon
#-----------------------
set -e
DAEMONS=('quantum-server' 'quantum-l3-agent' 'quantum-dhcp-agent' 'quantum-metadata-agent' 'quantum-lbaas-agent')
for daemon in "${DAEMONS[@]}"; do
    if pidof -x $daemon > /dev/null; then
        echo "OK"
    else
        echo "ERROR: ${daemon} IS NOT RUNNING"
        exit 1
    fi
done
